### ISSUE TITLE
关于系统权限配置的问题

### ISSUE THREAD

**Issue by KingOFCoffe** [chi8708/NBCZ#2]
你好，很感谢你的代码分享，有几个问题请教一下；
        1、关于“授权”操作，  目前系统中，支持用户授权操作，和角色权限分配，如果一个新的用户，同时指定了角色权限和用户个人权限，会不会有冲突呢？  目前在系统中测试不了。
        2、新增了一个与“基础信息”并列的菜单栏，应该要如何给这新菜单分配权限呢？都指定了，但是，用除了admin的用户登录时，显示“没有访问的权限！”
      再次感谢你的分享，如果能有时间回答，不胜感激！个人QQ是（1207206442）

**Comment by chi8708** [comment]
是用户权限＋角色权限的并集。如Admin 属管理员角色，管理员 角色权限有FC000001， 用户权限有FC000002。 则Admin的权限为FC000001、FC000002
