### ISSUE TITLE
同一个用户分配多个角色，会出现登录失败的现象。

### ISSUE THREAD

**Issue by KingOFCoffe** [chi8708/NBCZ#3]
为同一个用户分配多个角色，在登录时，会登录获取角色，如果出现多个角色，会报错!

**Comment by chi8708** [comment]
谢谢 提醒。此bug已修复，请pull最新版

**Comment by KingOFCoffe** [comment]
还有一个问题重现步骤
 1、在顶部新建新建tab菜单后，且在新的tab栏增加左侧菜单； 
 2、新增用户，针对用户进行权限授权，此时如果仅仅授权新菜单的权限，登录后，会报“权限授权失败，请联系。。。”
3、如果同时给新用户分配了【用户信息】的权限，就可以正常查看，新菜单！
若能解决，不胜感激！
